package editor_1_1;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import org.jdesktop.swingx.border.DropShadowBorder; 

/**
 *
 * @author Samuele Pozzebon
 */
public class MainPage extends javax.swing.JFrame {
    /**
     * Creates new form MainPage
     */
    
    DropShadowBorder shadow; //ombra
        
    byte indx;
    
    Color defaultColor;     //colore di sfondo/primario
    Color mousePassedColor;   //colore di sfondo/secondario
    Color selectedColor;    //colore di sfondo/elemento selezionato
    Color textColor;        //colore dei testi
    
    Font mainF;
    Font subTitleFont;
    
    CheckBoxGenerator checkBoxTable;
    ReadLanguagesFile langRead;
    OutLanguagesFile langOut;
    List<ClassLanguages> langList;
    
    TranslationMenuGenerator tranTable;
    ReadTranslationsFile tranRead;
    OutTranslationsFile tranOut;
    List<ClassTranslations> tranList;
    
    ReadGeneralFile genRead;
    OutGeneralFile genOut;
    ClassGeneralSettings genSet;
    
    public MainPage() {
        initPersonalComponent();
        initComponents();
        preset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();
        JDialAddLang = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pnlTopHeader1 = new javax.swing.JPanel();
        exitButton1 = new javax.swing.JButton();
        barIcon1 = new javax.swing.JLabel();
        titleLbl1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jColorChooser = new javax.swing.JColorChooser();
        jDialog1 = new javax.swing.JDialog();
        pnlTopHeader = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();
        barIcon = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        headerLayPane = new javax.swing.JLayeredPane();
        langP = new javax.swing.JPanel();
        langL = new javax.swing.JLabel();
        fieldP = new javax.swing.JPanel();
        fieldL = new javax.swing.JLabel();
        collogP = new javax.swing.JPanel();
        collogL = new javax.swing.JLabel();
        lang = new javax.swing.JPanel();
        lblLang1 = new javax.swing.JLabel();
        pnlScrPnEX = new javax.swing.JPanel();
        scrollPaneLang = new javax.swing.JScrollPane();
        pnlScrPnIN = new javax.swing.JPanel();
        pnlBtnAddLang = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fiel = new javax.swing.JPanel();
        pnlScrTraEx = new javax.swing.JPanel();
        scrollPaneTran = new javax.swing.JScrollPane();
        pnlScrTraIn = new javax.swing.JPanel();
        lblAddField = new javax.swing.JLabel();
        collog = new javax.swing.JPanel();
        lblColBack = new javax.swing.JLabel();
        lblColText = new javax.swing.JLabel();
        lblColBox = new javax.swing.JLabel();
        lblColExHead = new javax.swing.JLabel();
        lblColInHead = new javax.swing.JLabel();
        lblColIcon = new javax.swing.JLabel();
        lblLogoDir = new javax.swing.JLabel();
        lblColExHeadChoose = new javax.swing.JLabel();
        lblColInHeadChoose = new javax.swing.JLabel();
        lblColBoxChoose = new javax.swing.JLabel();
        lblColTextChoose = new javax.swing.JLabel();
        lblColBackChoose = new javax.swing.JLabel();
        comBoxIcon = new javax.swing.JComboBox<>();
        lblColInHeadCode = new javax.swing.JLabel();
        lblColExHeadCode = new javax.swing.JLabel();
        lblColBoxCode = new javax.swing.JLabel();
        lblColTextCode = new javax.swing.JLabel();
        lblColBackCode = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblLogoChoose = new javax.swing.JLabel();
        lblDataPer = new javax.swing.JLabel();
        lblSubTColLog = new javax.swing.JLabel();
        lblSubTPri = new javax.swing.JLabel();
        lblPriInfo = new javax.swing.JLabel();
        lblUtlT = new javax.swing.JLabel();
        txtFPriInfo = new javax.swing.JTextField();
        txtFUtlT = new javax.swing.JTextField();
        lblSave = new javax.swing.JLabel();
        lblColTextAdv = new javax.swing.JLabel();
        lblColTextAdvChoos = new javax.swing.JLabel();
        lblColTextAdvCode = new javax.swing.JLabel();
        txtFDataPer = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        jFileChooser.setApproveButtonText("Aggiungi");
        jFileChooser.setCurrentDirectory(new java.io.File("C:\\Users\\Samuele Pozzebon\\Pictures"));
        jFileChooser.setPreferredSize(new java.awt.Dimension(570, 400));
        jFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooserActionPerformed(evt);
            }
        });
        jFileChooser.getAccessibleContext().setAccessibleParent(pnlTopHeader);
        jFileChooser.setLocation(0, 0);

        JDialAddLang.setLocation(new java.awt.Point(0, 0));
        JDialAddLang.setMinimumSize(new java.awt.Dimension(300, 200));
        JDialAddLang.setUndecorated(true);
        JDialAddLang.setResizable(false);
        JDialAddLang.setSize(new java.awt.Dimension(300, 200));
        JDialAddLang.getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(defaultColor));
        jPanel2.setMaximumSize(new java.awt.Dimension(300, 200));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 200));
        jPanel2.setLayout(null);

        jTextField1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jTextField1.setMaximumSize(new java.awt.Dimension(130, 20));
        jTextField1.setMinimumSize(new java.awt.Dimension(130, 20));
        jTextField1.setPreferredSize(new java.awt.Dimension(130, 20));
        jPanel2.add(jTextField1);
        jTextField1.setBounds(140, 50, 130, 20);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel2.setText("Nome della lingua:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 50, 100, 20);

        pnlTopHeader1.setBackground(new java.awt.Color(255, 255, 255));
        pnlTopHeader1.setMaximumSize(new java.awt.Dimension(300, 24));
        pnlTopHeader1.setMinimumSize(new java.awt.Dimension(300, 24));
        pnlTopHeader1.setPreferredSize(new java.awt.Dimension(298, 24));
        pnlTopHeader1.setLayout(null);

        exitButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor_1_1/closeIconEmpty.png"))); // NOI18N
        exitButton1.setToolTipText("");
        exitButton1.setBorder(null);
        exitButton1.setBorderPainted(false);
        exitButton1.setContentAreaFilled(false);
        exitButton1.setMaximumSize(new java.awt.Dimension(14, 14));
        exitButton1.setMinimumSize(new java.awt.Dimension(14, 14));
        exitButton1.setPreferredSize(new java.awt.Dimension(14, 14));
        exitButton1.setRolloverEnabled(false);
        exitButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButton1MouseExited(evt);
            }
        });
        exitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton1ActionPerformed(evt);
            }
        });
        pnlTopHeader1.add(exitButton1);
        exitButton1.setBounds(280, 5, 14, 14);

        barIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor_1_1/editor_icon.jpg"))); // NOI18N
        pnlTopHeader1.add(barIcon1);
        barIcon1.setBounds(3, 2, 20, 20);

        titleLbl1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        titleLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl1.setText("Aggiungi lingua");
        titleLbl1.setPreferredSize(new java.awt.Dimension(200, 25));
        titleLbl1.setRequestFocusEnabled(false);
        pnlTopHeader1.add(titleLbl1);
        titleLbl1.setBounds(49, 0, 200, 25);

        jPanel2.add(pnlTopHeader1);
        pnlTopHeader1.setBounds(1, 1, 298, 24);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(140, 100, 130, 20);

        jPanel3.setBackground(new java.awt.Color(96, 125, 139));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(96, 125, 139));
        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 239, 241));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Seleziona l'icona");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(20, 100, 100, 20);

        jPanel4.setBackground(new java.awt.Color(96, 125, 139));

        jLabel5.setBackground(new java.awt.Color(96, 125, 139));
        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 239, 241));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Aggiungi");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(100, 150, 100, 20);

        JDialAddLang.getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 300, 200);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Site editor");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(402, 623));
        setName("Site editor"); // NOI18N
        setUndecorated(true);
        setSize(new java.awt.Dimension(402, 623));
        getContentPane().setLayout(null);

        pnlTopHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlTopHeader.setMaximumSize(new java.awt.Dimension(402, 24));
        pnlTopHeader.setMinimumSize(new java.awt.Dimension(402, 24));
        pnlTopHeader.setPreferredSize(new java.awt.Dimension(402, 24));
        pnlTopHeader.setLayout(null);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor_1_1/closeIconEmpty.png"))); // NOI18N
        exitButton.setToolTipText("");
        exitButton.setBorder(null);
        exitButton.setBorderPainted(false);
        exitButton.setContentAreaFilled(false);
        exitButton.setMaximumSize(new java.awt.Dimension(14, 14));
        exitButton.setMinimumSize(new java.awt.Dimension(14, 14));
        exitButton.setPreferredSize(new java.awt.Dimension(14, 14));
        exitButton.setRolloverEnabled(false);
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
        });
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        pnlTopHeader.add(exitButton);
        exitButton.setBounds(383, 5, 14, 14);

        barIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor_1_1/editor_icon.jpg"))); // NOI18N
        pnlTopHeader.add(barIcon);
        barIcon.setBounds(3, 2, 20, 20);

        titleLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText(getTitle());
        titleLbl.setPreferredSize(new java.awt.Dimension(200, 25));
        titleLbl.setRequestFocusEnabled(false);
        pnlTopHeader.add(titleLbl);
        titleLbl.setBounds(101, 0, 200, 25);

        getContentPane().add(pnlTopHeader);
        pnlTopHeader.setBounds(0, 0, 402, 24);

        pnlMenu.setMaximumSize(new java.awt.Dimension(402, 542));
        pnlMenu.setMinimumSize(new java.awt.Dimension(402, 542));
        pnlMenu.setPreferredSize(new java.awt.Dimension(402, 599));
        pnlMenu.setLayout(null);

        headerLayPane.setBorder(shadow);
        headerLayPane.setForeground(textColor);
        headerLayPane.setFont(subTitleFont);
        headerLayPane.setMaximumSize(new java.awt.Dimension(402, 56));
        headerLayPane.setMinimumSize(new java.awt.Dimension(402, 56));

        langP.setBackground(selectedColor);
        langP.setMaximumSize(new java.awt.Dimension(134, 46));
        langP.setMinimumSize(new java.awt.Dimension(134, 46));
        langP.setPreferredSize(new java.awt.Dimension(134, 46));
        langP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                langPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                langPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                langPMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                langPMouseReleased(evt);
            }
        });

        langL.setFont(subTitleFont);
        langL.setForeground(textColor);
        langL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        langL.setLabelFor(langP);
        langL.setText("Lingue");
        langL.setPreferredSize(new java.awt.Dimension(134, 46));

        javax.swing.GroupLayout langPLayout = new javax.swing.GroupLayout(langP);
        langP.setLayout(langPLayout);
        langPLayout.setHorizontalGroup(
            langPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, langPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(langL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        langPLayout.setVerticalGroup(
            langPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(langPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(langL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        headerLayPane.add(langP);
        langP.setBounds(0, 0, 134, 46);
        langP.getAccessibleContext().setAccessibleName("Lingue");

        fieldP.setBackground(defaultColor);
        fieldP.setMaximumSize(new java.awt.Dimension(134, 46));
        fieldP.setMinimumSize(new java.awt.Dimension(134, 46));
        fieldP.setPreferredSize(new java.awt.Dimension(134, 46));
        fieldP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fieldPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fieldPMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fieldPMouseReleased(evt);
            }
        });

        fieldL.setFont(subTitleFont);
        fieldL.setForeground(textColor);
        fieldL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fieldL.setLabelFor(langP);
        fieldL.setText("Campi");
        fieldL.setMaximumSize(new java.awt.Dimension(134, 46));
        fieldL.setMinimumSize(new java.awt.Dimension(134, 46));
        fieldL.setPreferredSize(new java.awt.Dimension(134, 46));

        javax.swing.GroupLayout fieldPLayout = new javax.swing.GroupLayout(fieldP);
        fieldP.setLayout(fieldPLayout);
        fieldPLayout.setHorizontalGroup(
            fieldPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
            .addGroup(fieldPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fieldPLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fieldL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        fieldPLayout.setVerticalGroup(
            fieldPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
            .addGroup(fieldPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fieldPLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fieldL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        headerLayPane.add(fieldP);
        fieldP.setBounds(134, 0, 134, 46);
        fieldP.getAccessibleContext().setAccessibleName("Campi");

        collogP.setBackground(defaultColor);
        collogP.setMaximumSize(new java.awt.Dimension(134, 46));
        collogP.setMinimumSize(new java.awt.Dimension(134, 46));
        collogP.setPreferredSize(new java.awt.Dimension(134, 46));
        collogP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                collogPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                collogPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                collogPMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                collogPMouseReleased(evt);
            }
        });

        collogL.setFont(subTitleFont);
        collogL.setForeground(textColor);
        collogL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        collogL.setLabelFor(langP);
        collogL.setText("Colori e logo");
        collogL.setMaximumSize(new java.awt.Dimension(134, 46));
        collogL.setMinimumSize(new java.awt.Dimension(134, 46));
        collogL.setPreferredSize(new java.awt.Dimension(134, 46));
        collogL.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout collogPLayout = new javax.swing.GroupLayout(collogP);
        collogP.setLayout(collogPLayout);
        collogPLayout.setHorizontalGroup(
            collogPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(collogL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        collogPLayout.setVerticalGroup(
            collogPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(collogL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        headerLayPane.add(collogP);
        collogP.setBounds(268, 0, 134, 46);
        collogP.getAccessibleContext().setAccessibleName("Colori e logo");

        pnlMenu.add(headerLayPane);
        headerLayPane.setBounds(0, 0, 402, 56);

        lang.setMaximumSize(new java.awt.Dimension(402, 542));
        lang.setMinimumSize(new java.awt.Dimension(402, 542));
        lang.setPreferredSize(new java.awt.Dimension(402, 542));

        lblLang1.setFont(subTitleFont);
        lblLang1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLang1.setText("Seleziona le lingue da visualizzare");

        pnlScrPnEX.setPreferredSize(new java.awt.Dimension(402, 360));
        pnlScrPnEX.setLayout(null);

        scrollPaneLang.setMaximumSize(new java.awt.Dimension(350, 300));
        scrollPaneLang.setMinimumSize(new java.awt.Dimension(350, 300));
        scrollPaneLang.setOpaque(false);
        scrollPaneLang.setPreferredSize(new java.awt.Dimension(250, 300));

        pnlScrPnIN.setBackground(new java.awt.Color(255, 255, 255));
        pnlScrPnIN.setLayout(new java.awt.GridLayout(2, 0));
        scrollPaneLang.setViewportView(pnlScrPnIN);

        pnlScrPnEX.add(scrollPaneLang);
        scrollPaneLang.setBounds(76, 30, 250, 300);

        pnlBtnAddLang.setMaximumSize(new java.awt.Dimension(402, 107));
        pnlBtnAddLang.setMinimumSize(new java.awt.Dimension(402, 107));
        pnlBtnAddLang.setPreferredSize(new java.awt.Dimension(402, 107));
        pnlBtnAddLang.setLayout(null);

        jPanel1.setBackground(defaultColor);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMaximumSize(new java.awt.Dimension(150, 35));
        jPanel1.setMinimumSize(new java.awt.Dimension(150, 35));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setForeground(textColor);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aggiungi lingua");
        jLabel1.setMaximumSize(new java.awt.Dimension(150, 35));
        jLabel1.setMinimumSize(new java.awt.Dimension(150, 35));
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 35));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlBtnAddLang.add(jPanel1);
        jPanel1.setBounds(126, 20, 150, 35);

        javax.swing.GroupLayout langLayout = new javax.swing.GroupLayout(lang);
        lang.setLayout(langLayout);
        langLayout.setHorizontalGroup(
            langLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlScrPnEX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBtnAddLang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        langLayout.setVerticalGroup(
            langLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(langLayout.createSequentialGroup()
                .addComponent(lblLang1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlScrPnEX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlBtnAddLang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenu.add(lang);
        lang.setBounds(0, 56, 402, 542);

        fiel.setMaximumSize(new java.awt.Dimension(402, 542));
        fiel.setMinimumSize(new java.awt.Dimension(402, 542));
        fiel.setPreferredSize(new java.awt.Dimension(402, 542));
        fiel.setLayout(null);

        pnlScrTraEx.setPreferredSize(new java.awt.Dimension(350, 350));
        pnlScrTraEx.setLayout(null);

        scrollPaneTran.setAutoscrolls(true);
        scrollPaneTran.setPreferredSize(new java.awt.Dimension(350, 310));

        pnlScrTraIn.setBackground(new java.awt.Color(255, 255, 255));
        pnlScrTraIn.setLayout(new java.awt.GridLayout());
        scrollPaneTran.setViewportView(pnlScrTraIn);
        pnlScrTraIn.setSize(pnlScrTraIn.getWidth(), (tranTable.getRowHeight()*tranTable.getRowCount()));

        pnlScrTraEx.add(scrollPaneTran);
        scrollPaneTran.setBounds(0, 0, 350, 310);

        fiel.add(pnlScrTraEx);
        pnlScrTraEx.setBounds(26, 96, 350, 310);

        lblAddField.setBackground(new java.awt.Color(96, 125, 139));
        lblAddField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblAddField.setForeground(new java.awt.Color(236, 239, 241));
        lblAddField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddField.setText("Aggiungi campo");
        lblAddField.setMaximumSize(new java.awt.Dimension(150, 35));
        lblAddField.setMinimumSize(new java.awt.Dimension(150, 35));
        lblAddField.setOpaque(true);
        lblAddField.setPreferredSize(new java.awt.Dimension(150, 35));
        lblAddField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddFieldMouseClicked(evt);
            }
        });
        fiel.add(lblAddField);
        lblAddField.setBounds(126, 455, 150, 35);

        pnlMenu.add(fiel);
        fiel.setBounds(0, 56, 402, 542);

        collog.setMaximumSize(new java.awt.Dimension(402, 542));
        collog.setPreferredSize(new java.awt.Dimension(402, 542));

        lblColBack.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblColBack.setText("Colore di sfondo:");

        lblColText.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblColText.setText("Colore del testo:");

        lblColBox.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblColBox.setText("Colore box:");

        lblColExHead.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblColExHead.setText("Colore esterno dell'header:");

        lblColInHead.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblColInHead.setText("Colore interno dell'header:");

        lblColIcon.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblColIcon.setText("Tema delle icone:");

        lblLogoDir.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblLogoDir.setPreferredSize(new java.awt.Dimension(86, 20));

        lblColExHeadChoose.setBackground(new java.awt.Color(96, 125, 139));
        lblColExHeadChoose.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblColExHeadChoose.setForeground(new java.awt.Color(236, 239, 241));
        lblColExHeadChoose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColExHeadChoose.setText("Scegli il colore");
        lblColExHeadChoose.setOpaque(true);
        lblColExHeadChoose.setPreferredSize(new java.awt.Dimension(80, 20));

        lblColInHeadChoose.setBackground(new java.awt.Color(96, 125, 139));
        lblColInHeadChoose.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblColInHeadChoose.setForeground(new java.awt.Color(236, 239, 241));
        lblColInHeadChoose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColInHeadChoose.setText("Scegli il colore");
        lblColInHeadChoose.setOpaque(true);
        lblColInHeadChoose.setPreferredSize(new java.awt.Dimension(80, 20));

        lblColBoxChoose.setBackground(new java.awt.Color(96, 125, 139));
        lblColBoxChoose.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblColBoxChoose.setForeground(new java.awt.Color(236, 239, 241));
        lblColBoxChoose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColBoxChoose.setText("Scegli il colore");
        lblColBoxChoose.setOpaque(true);
        lblColBoxChoose.setPreferredSize(new java.awt.Dimension(80, 20));

        lblColTextChoose.setBackground(new java.awt.Color(96, 125, 139));
        lblColTextChoose.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblColTextChoose.setForeground(new java.awt.Color(236, 239, 241));
        lblColTextChoose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColTextChoose.setText("Scegli il colore");
        lblColTextChoose.setOpaque(true);
        lblColTextChoose.setPreferredSize(new java.awt.Dimension(80, 20));

        lblColBackChoose.setBackground(new java.awt.Color(96, 125, 139));
        lblColBackChoose.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblColBackChoose.setForeground(new java.awt.Color(236, 239, 241));
        lblColBackChoose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColBackChoose.setText("Scegli il colore");
        lblColBackChoose.setOpaque(true);
        lblColBackChoose.setPreferredSize(new java.awt.Dimension(80, 20));
        lblColBackChoose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblColBackChooseMouseClicked(evt);
            }
        });

        comBoxIcon.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        comBoxIcon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chiaro", "Scuro"}));
        comBoxIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxIconActionPerformed(evt);
            }
        });

        lblColInHeadCode.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblColInHeadCode.setOpaque(true);
        lblColInHeadCode.setPreferredSize(new java.awt.Dimension(86, 20));

        lblColExHeadCode.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblColExHeadCode.setOpaque(true);
        lblColExHeadCode.setPreferredSize(new java.awt.Dimension(86, 20));

        lblColBoxCode.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblColBoxCode.setOpaque(true);
        lblColBoxCode.setPreferredSize(new java.awt.Dimension(86, 20));

        lblColTextCode.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblColTextCode.setOpaque(true);
        lblColTextCode.setPreferredSize(new java.awt.Dimension(86, 20));

        lblColBackCode.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblColBackCode.setOpaque(true);
        lblColBackCode.setPreferredSize(new java.awt.Dimension(86, 20));

        lblLogo.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblLogo.setText("Logo aziendale:");

        lblLogoChoose.setBackground(new java.awt.Color(96, 125, 139));
        lblLogoChoose.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblLogoChoose.setForeground(new java.awt.Color(236, 239, 241));
        lblLogoChoose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogoChoose.setText("Scegli l'immagine");
        lblLogoChoose.setOpaque(true);
        lblLogoChoose.setPreferredSize(new java.awt.Dimension(90, 20));

        lblDataPer.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblDataPer.setText("Persistenza dei dati:");

        lblSubTColLog.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblSubTColLog.setText("Colori e logo");

        lblSubTPri.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblSubTPri.setText("Privacy");

        lblPriInfo.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblPriInfo.setText("Link informativa sulla privacy:");

        lblUtlT.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblUtlT.setText("Link termini di utilizzo:");

        txtFPriInfo.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtFPriInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFPriInfoActionPerformed(evt);
            }
        });

        txtFUtlT.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        lblSave.setBackground(new java.awt.Color(96, 125, 139));
        lblSave.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblSave.setForeground(new java.awt.Color(236, 239, 241));
        lblSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSave.setText("Salva");
        lblSave.setOpaque(true);
        lblSave.setPreferredSize(new java.awt.Dimension(60, 25));

        lblColTextAdv.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblColTextAdv.setText("Colore degli avvisi:");

        lblColTextAdvChoos.setBackground(new java.awt.Color(96, 125, 139));
        lblColTextAdvChoos.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblColTextAdvChoos.setForeground(new java.awt.Color(236, 239, 241));
        lblColTextAdvChoos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColTextAdvChoos.setText("Scegli il colore");
        lblColTextAdvChoos.setOpaque(true);
        lblColTextAdvChoos.setPreferredSize(new java.awt.Dimension(80, 20));

        lblColTextAdvCode.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblColTextAdvCode.setOpaque(true);
        lblColTextAdvCode.setPreferredSize(new java.awt.Dimension(86, 20));

        txtFDataPer.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtFDataPer.setMinimumSize(new java.awt.Dimension(50, 20));
        txtFDataPer.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel6.setText("giorni");

        jCheckBox1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jCheckBox1.setText("Per sempre");
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout collogLayout = new javax.swing.GroupLayout(collog);
        collog.setLayout(collogLayout);
        collogLayout.setHorizontalGroup(
            collogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(collogLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(lblSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(collogLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(collogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, collogLayout.createSequentialGroup()
                        .addGroup(collogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblColExHead)
                            .addComponent(lblColInHead)
                            .addComponent(lblColBox)
                            .addComponent(lblColText)
                            .addComponent(lblColBack)
                            .addComponent(lblColIcon)
                            .addComponent(lblLogo)
                            .addComponent(lblColTextAdv)
                            .addComponent(lblSubTPri)
                            .addComponent(lblSubTColLog))
                        .addGap(18, 18, 18)
                        .addGroup(collogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblColBoxChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(lblColInHeadChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(lblColExHeadChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(lblLogoChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(lblColTextChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(lblColBackChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(comBoxIcon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblColTextAdvChoos, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(collogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblColBackCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblColTextCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblColBoxCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblColExHeadCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblColInHeadCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLogoDir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblColTextAdvCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, collogLayout.createSequentialGroup()
                        .addGroup(collogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPriInfo)
                            .addComponent(lblUtlT)
                            .addComponent(lblDataPer))
                        .addGap(18, 18, 18)
                        .addGroup(collogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(collogLayout.createSequentialGroup()
                                .addComponent(txtFDataPer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBox1))
                            .addComponent(txtFUtlT)
                            .addComponent(txtFPriInfo))))
                .addGap(31, 31, 31))
        );
        collogLayout.setVerticalGroup(
            collogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(collogLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblSubTColLog)
                .addGap(18, 18, 18)
                .addGroup(collogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColBack)
                    .addComponent(lblColBackChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColBackCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(collogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColText)
                    .addComponent(lblColTextChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColTextCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(collogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(collogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblColTextAdv)
                        .addComponent(lblColTextAdvChoos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblColTextAdvCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(collogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColBox)
                    .addComponent(lblColBoxChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColBoxCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(collogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColExHead)
                    .addComponent(lblColExHeadChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColExHeadCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(collogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColInHead)
                    .addComponent(lblColInHeadChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColInHeadCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(collogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColIcon)
                    .addComponent(comBoxIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(collogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogoDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogo)
                    .addComponent(lblLogoChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblSubTPri)
                .addGap(18, 18, 18)
                .addGroup(collogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataPer)
                    .addComponent(txtFDataPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jCheckBox1))
                .addGap(18, 18, 18)
                .addGroup(collogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPriInfo)
                    .addComponent(txtFPriInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(collogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUtlT)
                    .addComponent(txtFUtlT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlMenu.add(collog);
        collog.setBounds(0, 56, 402, 542);

        getContentPane().add(pnlMenu);
        pnlMenu.setBounds(0, 24, 402, 599);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void langPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_langPMouseClicked
        if (indx != 0) {
            selection((byte) 0);
        }
    }//GEN-LAST:event_langPMouseClicked

    private void langPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_langPMouseEntered
        if (indx != 0) {
            langP.setBackground(mousePassedColor);
            langL.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_langPMouseEntered

    private void langPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_langPMouseExited
        if (indx != 0) {
            langP.setBackground(defaultColor);
            langL.setForeground(textColor);
        }
    }//GEN-LAST:event_langPMouseExited

    private void langPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_langPMouseReleased
        langP.setBackground(defaultColor);
        langL.setForeground(textColor);
    }//GEN-LAST:event_langPMouseReleased

    private void fieldPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldPMouseClicked
        if (indx != 1) {
            selection((byte) 1);
        }
    }//GEN-LAST:event_fieldPMouseClicked

    private void fieldPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldPMouseEntered
        if (indx != 1) {
            fieldP.setBackground(mousePassedColor);
            fieldL.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_fieldPMouseEntered

    private void fieldPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldPMouseExited
        if (indx != 1) {
            fieldP.setBackground(defaultColor);
            fieldL.setForeground(textColor);
        }
    }//GEN-LAST:event_fieldPMouseExited

    private void fieldPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldPMouseReleased
        fieldP.setBackground(defaultColor);
        fieldL.setForeground(textColor);
    }//GEN-LAST:event_fieldPMouseReleased

    private void collogPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_collogPMouseClicked
        if (indx != 2) {
            selection((byte) 2);
        }
    }//GEN-LAST:event_collogPMouseClicked

    private void collogPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_collogPMouseEntered
        if (indx != 2) {
            collogP.setBackground(mousePassedColor);
            collogL.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_collogPMouseEntered

    private void collogPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_collogPMouseExited
        if (indx != 2) {
            collogP.setBackground(defaultColor);
            collogL.setForeground(textColor);
        }
    }//GEN-LAST:event_collogPMouseExited

    private void collogPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_collogPMouseReleased
        collogP.setBackground(defaultColor);
        collogL.setForeground(textColor);
    }//GEN-LAST:event_collogPMouseReleased

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        exitButton.setIcon(new ImageIcon(getClass().getResource("/editor_1_1/closeIconCrossed.png")));
    }//GEN-LAST:event_exitButtonMouseEntered

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        exitButton.setIcon(new ImageIcon(getClass().getResource("/editor_1_1/closeIconEmpty.png")));
    }//GEN-LAST:event_exitButtonMouseExited

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        close();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        JDialAddLang.setVisible(true);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void exitButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButton1MouseEntered
        exitButton1.setIcon(new ImageIcon(getClass().getResource("/editor_1_1/closeIconCrossed.png")));
    }//GEN-LAST:event_exitButton1MouseEntered

    private void exitButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButton1MouseExited
        exitButton1.setIcon(new ImageIcon(getClass().getResource("/editor_1_1/closeIconEmpty.png")));
    }//GEN-LAST:event_exitButton1MouseExited

    private void exitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton1ActionPerformed
        JDialAddLang.setVisible(false);
    }//GEN-LAST:event_exitButton1ActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        jFileChooser.showOpenDialog(rootPane);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFileChooserActionPerformed

    private void comBoxIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxIconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comBoxIconActionPerformed

    private void txtFPriInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFPriInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFPriInfoActionPerformed

    private void lblColBackChooseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblColBackChooseMouseClicked
        jColorChooser.showDialog(rootPane, "Scegli il colore", Color.decode("#25252E"));
    }//GEN-LAST:event_lblColBackChooseMouseClicked

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        if(jCheckBox1.isSelected()) {txtFDataPer.setEnabled(false); txtFDataPer.setText(null);}
        else {txtFDataPer.setEnabled(true);};
    }//GEN-LAST:event_jCheckBox1StateChanged

    private void lblAddFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAddFieldMouseClicked
    
    private void initPersonalComponent() {
        langRead = new ReadLanguagesFile();
        langList = langRead.getList();
        
        tranRead = new ReadTranslationsFile();
        tranList = tranRead.getList();
        
        genRead = new ReadGeneralFile();
        //genSet = genRead.getSet();
        
        genSet = new ClassGeneralSettings(null, "Chiaro", null, null, null, null, null, Color.decode("#25252E"), Color.decode("#E6E6E6"), Color.decode("#7C7C85"), Color.decode("#E6E6E6"), Color.decode("#E6E6E6"), Color.decode("#E6E6E6"), 0);
        
        mainF = new Font("Sans Serif",Font.PLAIN, 15);
        subTitleFont = new Font("Sans Serif",Font.PLAIN, 19);
        
        checkBoxTable = new CheckBoxGenerator(langList);
        checkBoxTable.setFont(mainF);
        
        tranList = new ArrayList<>();
        String[] n = {"Name"};
        String[] s = {"Surname"};
        String[] c = {"Company"};
        String[] cr = {"Company referrer"};
        String[] r = {"Registration"};
        String[] kv = {"Kind of visit"};
        String[] cv = {"Corporate visit"};
        String[] a = {"Advice"};
        String[] o = {"Other"};
        String[] tu = {"I have read and agree to terms of use and privacy"};
        String[] fm = {"All fields are mandatory"};
        String[] at = {"We are almost there"};
        String[] sqr = {"show the following QR code to the secretary"};
        String[] d = {"Download"};
        
        tranList.add(new ClassTranslations("Registrazione", r));
        tranList.add(new ClassTranslations("Ho letto ed acconsento ai termini di utilizzo e alle condizioni sulla privacy", tu));
        tranList.add(new ClassTranslations("Tutti i campi sono obbligatori", fm));
        tranList.add(new ClassTranslations("Ci siamo quasi", at));
        tranList.add(new ClassTranslations("mostra il codice QR seguente alla segretaria", sqr));
        tranList.add(new ClassTranslations("Scarica", d));
        tranList.add(new ClassTranslations("Tipo di visita", kv));
        tranList.add(new ClassTranslations("Visita aziendale", cv));
        tranList.add(new ClassTranslations("Consulenza", a));
        tranList.add(new ClassTranslations("Altro", o));
        tranList.add(new ClassTranslations("Nome", n));
        tranList.add(new ClassTranslations("Cognome", s));
        tranList.add(new ClassTranslations("Azienda", c));
        tranList.add(new ClassTranslations("Referente aziendale", cr));
        
        
        
        
        /*if (tranList != null) {checkBoxTable = new CheckBoxGenerator(tranList);}
        else {
            tranList = new ArrayList<>();
            tranList.add(new ClassTranslations("Nome", "Name"));
            tranList.add(new ClassTranslations("Cgnome", "Surname"));
            tranTable = new tranTable(tranList, checkBoxTable.getLanguages(langList));
        };*/
        tranTable = new TranslationMenuGenerator(tranList, checkBoxTable.getLanguages(langList));
        tranTable.setFont(new Font("Sans Serif",Font.PLAIN, 11));
        
        defaultColor = Color.decode("#607D8B"); //sclego il colore primario
        mousePassedColor = Color.decode("#5E7A88");
        selectedColor = Color.decode("#718D9C");
        textColor = Color.decode("#ECEFF1"); //sclego il colore dei testi
        
        shadow = new DropShadowBorder();
        //creazione e impostazione dell'ombra
        shadow.setShadowColor(Color.BLACK);
        shadow.setShowLeftShadow(true);
        shadow.setShowRightShadow(true);
        shadow.setShowTopShadow(false);
        shadow.setShowBottomShadow(true);
        shadow.setShadowSize(10);
        shadow.setCornerSize(25);
    }
    
    
    private void preset() {
        lang.setVisible(true);
        fiel.setVisible(false);
        collog.setVisible(false);
        
        //scrollPaneTran.setLayout(new GridLayout(1, 0));
        //scrollPaneTran.add(tranTable);
        panelHeight();
        pnlScrPnIN.add(checkBoxTable);
        pnlScrTraIn.add(tranTable);
        //JDialAddLang.setLocationRelativeTo(null);
        
        
        reorderCol();
    }
    
    private void selection(byte finalIndx) {
        switch (indx) {
            case 0: {
                langP.setBackground(defaultColor);
                langL.setForeground(textColor);
            }break;
            case 1: {
                fieldP.setBackground(defaultColor);
                fieldL.setForeground(textColor);
            }break;
            case 2: {
                collogP.setBackground(defaultColor);
                collogL.setForeground(textColor);
            }break;
        }
        switch (finalIndx) {
            case 0: {
                langP.setBackground(selectedColor);
                langL.setForeground(textColor);
                lang.setVisible(true);
                fiel.setVisible(false);
                collog.setVisible(false);
            }break;
            case 1: {
                fieldP.setBackground(selectedColor);
                fieldL.setForeground(textColor);
                lang.setVisible(false);
                fiel.setVisible(true);
                collog.setVisible(false);
            }break;
            case 2: {
                collogP.setBackground(selectedColor);
                collogL.setForeground(textColor);
                lang.setVisible(false);
                fiel.setVisible(false);
                collog.setVisible(true);
            }break;
        }
        
        indx = finalIndx;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog JDialAddLang;
    private javax.swing.JLabel barIcon;
    private javax.swing.JLabel barIcon1;
    private javax.swing.JPanel collog;
    private javax.swing.JLabel collogL;
    private javax.swing.JPanel collogP;
    private javax.swing.JComboBox<String> comBoxIcon;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton exitButton1;
    private javax.swing.JPanel fiel;
    private javax.swing.JLabel fieldL;
    private javax.swing.JPanel fieldP;
    private javax.swing.JLayeredPane headerLayPane;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JColorChooser jColorChooser;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel lang;
    private javax.swing.JLabel langL;
    private javax.swing.JPanel langP;
    private javax.swing.JLabel lblAddField;
    private javax.swing.JLabel lblColBack;
    private javax.swing.JLabel lblColBackChoose;
    private javax.swing.JLabel lblColBackCode;
    private javax.swing.JLabel lblColBox;
    private javax.swing.JLabel lblColBoxChoose;
    private javax.swing.JLabel lblColBoxCode;
    private javax.swing.JLabel lblColExHead;
    private javax.swing.JLabel lblColExHeadChoose;
    private javax.swing.JLabel lblColExHeadCode;
    private javax.swing.JLabel lblColIcon;
    private javax.swing.JLabel lblColInHead;
    private javax.swing.JLabel lblColInHeadChoose;
    private javax.swing.JLabel lblColInHeadCode;
    private javax.swing.JLabel lblColText;
    private javax.swing.JLabel lblColTextAdv;
    private javax.swing.JLabel lblColTextAdvChoos;
    private javax.swing.JLabel lblColTextAdvCode;
    private javax.swing.JLabel lblColTextChoose;
    private javax.swing.JLabel lblColTextCode;
    private javax.swing.JLabel lblDataPer;
    private javax.swing.JLabel lblLang1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogoChoose;
    private javax.swing.JLabel lblLogoDir;
    private javax.swing.JLabel lblPriInfo;
    private javax.swing.JLabel lblSave;
    private javax.swing.JLabel lblSubTColLog;
    private javax.swing.JLabel lblSubTPri;
    private javax.swing.JLabel lblUtlT;
    private javax.swing.JPanel pnlBtnAddLang;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlScrPnEX;
    private javax.swing.JPanel pnlScrPnIN;
    private javax.swing.JPanel pnlScrTraEx;
    private javax.swing.JPanel pnlScrTraIn;
    private javax.swing.JPanel pnlTopHeader;
    private javax.swing.JPanel pnlTopHeader1;
    private javax.swing.JScrollPane scrollPaneLang;
    private javax.swing.JScrollPane scrollPaneTran;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel titleLbl1;
    private javax.swing.JTextField txtFDataPer;
    private javax.swing.JTextField txtFPriInfo;
    private javax.swing.JTextField txtFUtlT;
    // End of variables declaration//GEN-END:variables

    private void close() {
        tranOut = new OutTranslationsFile(tranList);
        langOut = new OutLanguagesFile(langList);
        System.out.println(pnlScrTraIn.getHeight());
        System.out.println("closing");
        System.exit(0);
    }

    private void reorderCol() {
        lblColBackCode.setBackground(genSet.getBackgroundColor());
        lblColBoxCode.setBackground(genSet.getBox());
        lblColExHeadCode.setBackground(genSet.getHeadEx());
        lblColInHeadCode.setBackground(genSet.getHeadIn());
        lblColTextAdvCode.setBackground(genSet.getTextAdv());
        lblColTextCode.setBackground(genSet.getTextMain());
        if (genSet.getPersitance() == 0) {txtFDataPer.setText(null); jCheckBox1.setSelected(true);}
        else {txtFDataPer.setText(Integer.toString(genSet.getPersitance())); jCheckBox1.setSelected(false);};
        lblLogoDir.setText(genSet.getLogo());
        txtFPriInfo.setText(genSet.getInfoLink());
        txtFUtlT.setText(genSet.getTermsLink());
        if(genSet.getIconPack().equals("Chiaro")) {comBoxIcon.setSelectedIndex(0);}
        else {comBoxIcon.setSelectedIndex(1);};
    }

    private void panelHeight() {
        pnlScrPnIN.repaint(0,0,pnlScrPnIN.getWidth(), checkBoxTable.getRowHeight()*checkBoxTable.getRowCount());
        pnlScrTraIn.repaint(0,0,pnlScrTraIn.getWidth(), (tranTable.getRowHeight()*tranTable.getRowCount()));
    }
}
