package editor_1_1;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import org.jdesktop.swingx.border.DropShadowBorder; 

/**
 *
 * @author Samuele Pozzebon
 */
public class MainPage extends javax.swing.JFrame {
    /**
     * Creates new form MainPage
     */
    
    DropShadowBorder shadow; //ombra
        
    byte indx;
    
    Color defaultColor;     //colore di sfondo/primario
    Color mousePassedColor;   //colore di sfondo/secondario
    Color selectedColor;    //colore di sfondo/elemento selezionato
    Color textColor;        //colore dei testi
    
    Font mainF;
    Font subTitleFont;
    
    CheckBoxGenerator checkBoxTable;
    
    ReadLanguagesFile langRead;
    OutLanguagesFile langOut;
    List<ClassLanguages> langList;
    List<ClassTranslations> tranList;
    
    public MainPage() {
        initPersonalComponent();
        initComponents();
        preset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pnlTopHeader1 = new javax.swing.JPanel();
        exitButton1 = new javax.swing.JButton();
        barIcon1 = new javax.swing.JLabel();
        titleLbl1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pnlTopHeader = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();
        barIcon = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        leftLayPane = new javax.swing.JLayeredPane();
        leftPane = new javax.swing.JPanel();
        previewLayPane = new javax.swing.JLayeredPane();
        mobileFrame = new javax.swing.JLabel();
        mobileBack = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        headerLayPane = new javax.swing.JLayeredPane();
        langP = new javax.swing.JPanel();
        langL = new javax.swing.JLabel();
        fieldP = new javax.swing.JPanel();
        fieldL = new javax.swing.JLabel();
        collogP = new javax.swing.JPanel();
        collogL = new javax.swing.JLabel();
        lang = new javax.swing.JPanel();
        lblLang1 = new javax.swing.JLabel();
        pnlScrPnEX = new javax.swing.JPanel();
        scrollPaneLang = new javax.swing.JScrollPane();
        pnlScrPnIN = new javax.swing.JPanel();
        pnlBtnAdd = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fiel = new javax.swing.JPanel();
        pnlScrTraEx = new javax.swing.JPanel();
        scrollPaneTran = new javax.swing.JScrollPane();
        pnlScrTraIn = new javax.swing.JPanel();
        collog = new javax.swing.JPanel();

        jFileChooser1.setApproveButtonText("");
        jFileChooser1.setCurrentDirectory(new java.io.File("C:\\Users\\Samuele Pozzebon\\Pictures"));

        jDialog1.setAlwaysOnTop(true);
        jDialog1.setLocation(new java.awt.Point(0, 0));
        jDialog1.setMaximumSize(new java.awt.Dimension(300, 200));
        jDialog1.setMinimumSize(new java.awt.Dimension(300, 200));
        jDialog1.setUndecorated(true);
        jDialog1.setPreferredSize(new java.awt.Dimension(300, 200));
        jDialog1.setResizable(false);
        jDialog1.setSize(new java.awt.Dimension(300, 200));
        jDialog1.getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(defaultColor));
        jPanel2.setMaximumSize(new java.awt.Dimension(300, 200));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 200));
        jPanel2.setLayout(null);

        jTextField1.setMaximumSize(new java.awt.Dimension(130, 20));
        jTextField1.setMinimumSize(new java.awt.Dimension(130, 20));
        jTextField1.setPreferredSize(new java.awt.Dimension(130, 20));
        jPanel2.add(jTextField1);
        jTextField1.setBounds(140, 50, 130, 20);

        jLabel2.setText("Nome della lingua:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 50, 87, 20);

        pnlTopHeader1.setBackground(new java.awt.Color(255, 255, 255));
        pnlTopHeader1.setMaximumSize(new java.awt.Dimension(300, 24));
        pnlTopHeader1.setMinimumSize(new java.awt.Dimension(300, 24));
        pnlTopHeader1.setPreferredSize(new java.awt.Dimension(298, 24));
        pnlTopHeader1.setLayout(null);

        exitButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor_1_1/closeIconEmpty.png"))); // NOI18N
        exitButton1.setToolTipText("");
        exitButton1.setBorder(null);
        exitButton1.setBorderPainted(false);
        exitButton1.setContentAreaFilled(false);
        exitButton1.setMaximumSize(new java.awt.Dimension(14, 14));
        exitButton1.setMinimumSize(new java.awt.Dimension(14, 14));
        exitButton1.setPreferredSize(new java.awt.Dimension(14, 14));
        exitButton1.setRolloverEnabled(false);
        exitButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButton1MouseExited(evt);
            }
        });
        exitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton1ActionPerformed(evt);
            }
        });
        pnlTopHeader1.add(exitButton1);
        exitButton1.setBounds(280, 5, 14, 14);

        barIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor_1_1/editor_icon.jpg"))); // NOI18N
        pnlTopHeader1.add(barIcon1);
        barIcon1.setBounds(3, 2, 20, 20);

        titleLbl1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        titleLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl1.setText("Aggiungi lingua");
        titleLbl1.setPreferredSize(new java.awt.Dimension(200, 25));
        titleLbl1.setRequestFocusEnabled(false);
        pnlTopHeader1.add(titleLbl1);
        titleLbl1.setBounds(49, 0, 200, 25);

        jPanel2.add(pnlTopHeader1);
        pnlTopHeader1.setBounds(1, 1, 298, 24);

        jButton1.setText("Seleziona l'icona");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(20, 100, 109, 23);

        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(160, 100, 120, 20);

        jDialog1.getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 300, 200);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Site editor");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(804, 623));
        setName("Site editor"); // NOI18N
        setUndecorated(true);
        setSize(new java.awt.Dimension(804, 623));
        getContentPane().setLayout(null);

        pnlTopHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlTopHeader.setMaximumSize(new java.awt.Dimension(804, 25));
        pnlTopHeader.setMinimumSize(new java.awt.Dimension(804, 25));
        pnlTopHeader.setPreferredSize(new java.awt.Dimension(804, 24));
        pnlTopHeader.setLayout(null);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor_1_1/closeIconEmpty.png"))); // NOI18N
        exitButton.setToolTipText("");
        exitButton.setBorder(null);
        exitButton.setBorderPainted(false);
        exitButton.setContentAreaFilled(false);
        exitButton.setMaximumSize(new java.awt.Dimension(14, 14));
        exitButton.setMinimumSize(new java.awt.Dimension(14, 14));
        exitButton.setPreferredSize(new java.awt.Dimension(14, 14));
        exitButton.setRolloverEnabled(false);
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
        });
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        pnlTopHeader.add(exitButton);
        exitButton.setBounds(784, 5, 14, 14);

        barIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor_1_1/editor_icon.jpg"))); // NOI18N
        pnlTopHeader.add(barIcon);
        barIcon.setBounds(3, 2, 20, 20);

        titleLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText(getTitle());
        titleLbl.setPreferredSize(new java.awt.Dimension(200, 25));
        titleLbl.setRequestFocusEnabled(false);
        pnlTopHeader.add(titleLbl);
        titleLbl.setBounds(302, 0, 200, 25);

        getContentPane().add(pnlTopHeader);
        pnlTopHeader.setBounds(0, 0, 804, 24);

        leftLayPane.setAlignmentX(0.0F);
        leftLayPane.setAlignmentY(0.0F);
        leftLayPane.setMaximumSize(new java.awt.Dimension(402, 598));
        leftLayPane.setMinimumSize(new java.awt.Dimension(402, 598));
        leftLayPane.setLayout(new java.awt.BorderLayout());

        leftPane.setMaximumSize(new java.awt.Dimension(400, 542));
        leftPane.setMinimumSize(new java.awt.Dimension(400, 542));
        leftPane.setRequestFocusEnabled(false);
        leftPane.setLayout(null);

        previewLayPane.setBorder(shadow);
        previewLayPane.setMaximumSize(new java.awt.Dimension(400, 598));
        previewLayPane.setMinimumSize(new java.awt.Dimension(400, 598));

        mobileFrame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mobileFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor_1_1/mobileFrame.png"))); // NOI18N
        previewLayPane.add(mobileFrame);
        mobileFrame.setBounds(0, 0, 400, 542);
        previewLayPane.setLayer(mobileFrame, javax.swing.JLayeredPane.PALETTE_LAYER);

        mobileBack.setBackground(new java.awt.Color(0, 0, 0));
        mobileBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mobileBack.setMaximumSize(new java.awt.Dimension(169, 304));
        mobileBack.setMinimumSize(new java.awt.Dimension(169, 304));
        mobileBack.setOpaque(true);
        mobileBack.setPreferredSize(new java.awt.Dimension(169, 304));
        previewLayPane.add(mobileBack);
        mobileBack.setBounds(115, 117, 169, 304);

        leftPane.add(previewLayPane);
        previewLayPane.setBounds(0, 0, 400, 598);

        leftLayPane.add(leftPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(leftLayPane);
        leftLayPane.setBounds(0, 24, 402, 619);

        pnlMenu.setMaximumSize(new java.awt.Dimension(402, 542));
        pnlMenu.setMinimumSize(new java.awt.Dimension(402, 542));
        pnlMenu.setPreferredSize(new java.awt.Dimension(402, 542));
        pnlMenu.setLayout(null);

        headerLayPane.setBorder(shadow);
        headerLayPane.setForeground(textColor);
        headerLayPane.setFont(subTitleFont);
        headerLayPane.setMaximumSize(new java.awt.Dimension(402, 56));
        headerLayPane.setMinimumSize(new java.awt.Dimension(402, 56));

        langP.setBackground(selectedColor);
        langP.setMaximumSize(new java.awt.Dimension(134, 46));
        langP.setMinimumSize(new java.awt.Dimension(134, 46));
        langP.setPreferredSize(new java.awt.Dimension(134, 46));
        langP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                langPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                langPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                langPMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                langPMouseReleased(evt);
            }
        });

        langL.setFont(subTitleFont);
        langL.setForeground(textColor);
        langL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        langL.setLabelFor(langP);
        langL.setText("Lingue");
        langL.setPreferredSize(new java.awt.Dimension(134, 46));

        javax.swing.GroupLayout langPLayout = new javax.swing.GroupLayout(langP);
        langP.setLayout(langPLayout);
        langPLayout.setHorizontalGroup(
            langPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, langPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(langL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        langPLayout.setVerticalGroup(
            langPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(langPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(langL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        headerLayPane.add(langP);
        langP.setBounds(0, 0, 134, 46);
        langP.getAccessibleContext().setAccessibleName("Lingue");

        fieldP.setBackground(defaultColor);
        fieldP.setMaximumSize(new java.awt.Dimension(134, 46));
        fieldP.setMinimumSize(new java.awt.Dimension(134, 46));
        fieldP.setPreferredSize(new java.awt.Dimension(134, 46));
        fieldP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fieldPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fieldPMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fieldPMouseReleased(evt);
            }
        });

        fieldL.setFont(subTitleFont);
        fieldL.setForeground(textColor);
        fieldL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fieldL.setLabelFor(langP);
        fieldL.setText("Campi");
        fieldL.setMaximumSize(new java.awt.Dimension(134, 46));
        fieldL.setMinimumSize(new java.awt.Dimension(134, 46));
        fieldL.setPreferredSize(new java.awt.Dimension(134, 46));

        javax.swing.GroupLayout fieldPLayout = new javax.swing.GroupLayout(fieldP);
        fieldP.setLayout(fieldPLayout);
        fieldPLayout.setHorizontalGroup(
            fieldPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
            .addGroup(fieldPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fieldPLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fieldL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        fieldPLayout.setVerticalGroup(
            fieldPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
            .addGroup(fieldPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fieldPLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fieldL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        headerLayPane.add(fieldP);
        fieldP.setBounds(134, 0, 134, 46);
        fieldP.getAccessibleContext().setAccessibleName("Campi");

        collogP.setBackground(defaultColor);
        collogP.setMaximumSize(new java.awt.Dimension(134, 46));
        collogP.setMinimumSize(new java.awt.Dimension(134, 46));
        collogP.setPreferredSize(new java.awt.Dimension(134, 46));
        collogP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                collogPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                collogPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                collogPMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                collogPMouseReleased(evt);
            }
        });

        collogL.setFont(subTitleFont);
        collogL.setForeground(textColor);
        collogL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        collogL.setLabelFor(langP);
        collogL.setText("Colori e logo");
        collogL.setMaximumSize(new java.awt.Dimension(134, 46));
        collogL.setMinimumSize(new java.awt.Dimension(134, 46));
        collogL.setPreferredSize(new java.awt.Dimension(134, 46));
        collogL.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout collogPLayout = new javax.swing.GroupLayout(collogP);
        collogP.setLayout(collogPLayout);
        collogPLayout.setHorizontalGroup(
            collogPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(collogL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        collogPLayout.setVerticalGroup(
            collogPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(collogL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        headerLayPane.add(collogP);
        collogP.setBounds(268, 0, 134, 46);
        collogP.getAccessibleContext().setAccessibleName("Colori e logo");

        pnlMenu.add(headerLayPane);
        headerLayPane.setBounds(0, 0, 402, 56);

        lang.setMaximumSize(new java.awt.Dimension(402, 542));
        lang.setMinimumSize(new java.awt.Dimension(402, 542));
        lang.setPreferredSize(new java.awt.Dimension(402, 542));

        lblLang1.setFont(subTitleFont);
        lblLang1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLang1.setText("Seleziona le lingue da visualizzare");

        pnlScrPnEX.setPreferredSize(new java.awt.Dimension(402, 360));
        pnlScrPnEX.setLayout(null);

        scrollPaneLang.setMaximumSize(new java.awt.Dimension(350, 300));
        scrollPaneLang.setMinimumSize(new java.awt.Dimension(350, 300));
        scrollPaneLang.setPreferredSize(new java.awt.Dimension(250, 300));

        pnlScrPnIN.setLayout(new java.awt.GridLayout(2, 0));
        scrollPaneLang.setViewportView(pnlScrPnIN);

        pnlScrPnEX.add(scrollPaneLang);
        scrollPaneLang.setBounds(76, 30, 250, 300);

        pnlBtnAdd.setMaximumSize(new java.awt.Dimension(402, 107));
        pnlBtnAdd.setMinimumSize(new java.awt.Dimension(402, 107));
        pnlBtnAdd.setPreferredSize(new java.awt.Dimension(402, 107));
        pnlBtnAdd.setLayout(null);

        jPanel1.setBackground(defaultColor);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMaximumSize(new java.awt.Dimension(150, 35));
        jPanel1.setMinimumSize(new java.awt.Dimension(150, 35));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setFont(subTitleFont);
        jLabel1.setForeground(textColor);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aggiungi lingua");
        jLabel1.setMaximumSize(new java.awt.Dimension(150, 35));
        jLabel1.setMinimumSize(new java.awt.Dimension(150, 35));
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 35));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlBtnAdd.add(jPanel1);
        jPanel1.setBounds(126, 20, 150, 35);

        javax.swing.GroupLayout langLayout = new javax.swing.GroupLayout(lang);
        lang.setLayout(langLayout);
        langLayout.setHorizontalGroup(
            langLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlScrPnEX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBtnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        langLayout.setVerticalGroup(
            langLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(langLayout.createSequentialGroup()
                .addComponent(lblLang1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlScrPnEX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlBtnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenu.add(lang);
        lang.setBounds(0, 56, 402, 542);

        fiel.setMaximumSize(new java.awt.Dimension(402, 542));
        fiel.setMinimumSize(new java.awt.Dimension(402, 542));
        fiel.setPreferredSize(new java.awt.Dimension(402, 542));
        fiel.setLayout(null);

        pnlScrTraEx.setPreferredSize(new java.awt.Dimension(350, 350));
        pnlScrTraEx.setLayout(null);

        javax.swing.GroupLayout pnlScrTraInLayout = new javax.swing.GroupLayout(pnlScrTraIn);
        pnlScrTraIn.setLayout(pnlScrTraInLayout);
        pnlScrTraInLayout.setHorizontalGroup(
            pnlScrTraInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );
        pnlScrTraInLayout.setVerticalGroup(
            pnlScrTraInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        scrollPaneTran.setViewportView(pnlScrTraIn);

        pnlScrTraEx.add(scrollPaneTran);
        scrollPaneTran.setBounds(0, 0, 350, 350);

        fiel.add(pnlScrTraEx);
        pnlScrTraEx.setBounds(26, 96, 350, 350);

        pnlMenu.add(fiel);
        fiel.setBounds(0, 56, 402, 542);

        collog.setMaximumSize(new java.awt.Dimension(402, 542));
        collog.setPreferredSize(new java.awt.Dimension(402, 542));

        javax.swing.GroupLayout collogLayout = new javax.swing.GroupLayout(collog);
        collog.setLayout(collogLayout);
        collogLayout.setHorizontalGroup(
            collogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        collogLayout.setVerticalGroup(
            collogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );

        pnlMenu.add(collog);
        collog.setBounds(0, 56, 402, 542);

        getContentPane().add(pnlMenu);
        pnlMenu.setBounds(402, 24, 402, 619);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void langPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_langPMouseClicked
        if (indx != 0) {
            selection((byte) 0);
        }
    }//GEN-LAST:event_langPMouseClicked

    private void langPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_langPMouseEntered
        if (indx != 0) {
            langP.setBackground(mousePassedColor);
            langL.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_langPMouseEntered

    private void langPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_langPMouseExited
        if (indx != 0) {
            langP.setBackground(defaultColor);
            langL.setForeground(textColor);
        }
    }//GEN-LAST:event_langPMouseExited

    private void langPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_langPMouseReleased
        langP.setBackground(defaultColor);
        langL.setForeground(textColor);
    }//GEN-LAST:event_langPMouseReleased

    private void fieldPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldPMouseClicked
        if (indx != 1) {
            selection((byte) 1);
        }
    }//GEN-LAST:event_fieldPMouseClicked

    private void fieldPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldPMouseEntered
        if (indx != 1) {
            fieldP.setBackground(mousePassedColor);
            fieldL.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_fieldPMouseEntered

    private void fieldPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldPMouseExited
        if (indx != 1) {
            fieldP.setBackground(defaultColor);
            fieldL.setForeground(textColor);
        }
    }//GEN-LAST:event_fieldPMouseExited

    private void fieldPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldPMouseReleased
        fieldP.setBackground(defaultColor);
        fieldL.setForeground(textColor);
    }//GEN-LAST:event_fieldPMouseReleased

    private void collogPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_collogPMouseClicked
        if (indx != 2) {
            selection((byte) 2);
        }
    }//GEN-LAST:event_collogPMouseClicked

    private void collogPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_collogPMouseEntered
        if (indx != 2) {
            collogP.setBackground(mousePassedColor);
            collogL.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_collogPMouseEntered

    private void collogPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_collogPMouseExited
        if (indx != 2) {
            collogP.setBackground(defaultColor);
            collogL.setForeground(textColor);
        }
    }//GEN-LAST:event_collogPMouseExited

    private void collogPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_collogPMouseReleased
        collogP.setBackground(defaultColor);
        collogL.setForeground(textColor);
    }//GEN-LAST:event_collogPMouseReleased

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        exitButton.setIcon(new ImageIcon(getClass().getResource("/editor_1_1/closeIconCrossed.png")));
    }//GEN-LAST:event_exitButtonMouseEntered

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        exitButton.setIcon(new ImageIcon(getClass().getResource("/editor_1_1/closeIconEmpty.png")));
    }//GEN-LAST:event_exitButtonMouseExited

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        close();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void exitButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButton1MouseEntered
        exitButton1.setIcon(new ImageIcon(getClass().getResource("/editor_1_1/closeIconCrossed.png")));
    }//GEN-LAST:event_exitButton1MouseEntered

    private void exitButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButton1MouseExited
        exitButton1.setIcon(new ImageIcon(getClass().getResource("/editor_1_1/closeIconEmpty.png")));
    }//GEN-LAST:event_exitButton1MouseExited

    private void exitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton1ActionPerformed
        jDialog1.setVisible(false);
    }//GEN-LAST:event_exitButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jFileChooser1.showDialog(jPanel1, "Scegli l'immagine");
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void initPersonalComponent() {
        langRead = new ReadLanguagesFile();
        langList = langRead.getList();
        mainF = new Font("Sans Serif",Font.PLAIN, 15);
        subTitleFont = new Font("Sans Serif",Font.PLAIN, 19);
        
        checkBoxTable = new CheckBoxGenerator(langList);
        checkBoxTable.setFont(mainF);
        if (tranList != null) {checkBoxTable = new CheckBoxGenerator(tranList);}
        else {
            tranList = new ArrayList<>();
            tranList.add(new ClassTranslations("Nome", "Name"));
            tranList.add(new ClassTranslations("Cgnome", "Surname"));
            tranTable = new tranTable(tranList, checkBoxTable.getLanguages(langList));
        };
        tranTable = new TranslationMenuGenerator(tranList, checkBoxTable.getLanguages(langList));
        tranTable.setFont(mainF);
        
        defaultColor = Color.decode("#607D8B"); //sclego il colore primario
        mousePassedColor = Color.decode("#5E7A88");
        selectedColor = Color.decode("#718D9C");
        textColor = Color.decode("#ECEFF1"); //sclego il colore dei testi
        
        shadow = new DropShadowBorder();
        //creazione e impostazione dell'ombra
        shadow.setShadowColor(Color.BLACK);
        shadow.setShowLeftShadow(true);
        shadow.setShowRightShadow(true);
        shadow.setShowTopShadow(false);
        shadow.setShowBottomShadow(true);
        shadow.setShadowSize(10);
        shadow.setCornerSize(25);
    }
    
    
    private void preset() {
        lang.setVisible(true);
        fiel.setVisible(false);
        collog.setVisible(false);
        
        pnlScrPnIN.add(checkBoxTable);
        
        jDialog1.setLocationRelativeTo(null);
    }
    
    private void selection(byte finalIndx) {
        switch (indx) {
            case 0: {
                langP.setBackground(defaultColor);
                langL.setForeground(textColor);
            }break;
            case 1: {
                fieldP.setBackground(defaultColor);
                fieldL.setForeground(textColor);
            }break;
            case 2: {
                collogP.setBackground(defaultColor);
                collogL.setForeground(textColor);
            }break;
        }
        switch (finalIndx) {
            case 0: {
                langP.setBackground(selectedColor);
                langL.setForeground(textColor);
                lang.setVisible(true);
                fiel.setVisible(false);
                collog.setVisible(false);
            }break;
            case 1: {
                fieldP.setBackground(selectedColor);
                fieldL.setForeground(textColor);
                lang.setVisible(false);
                fiel.setVisible(true);
                collog.setVisible(false);
            }break;
            case 2: {
                collogP.setBackground(selectedColor);
                collogL.setForeground(textColor);
                lang.setVisible(false);
                fiel.setVisible(false);
                collog.setVisible(true);
            }break;
        }
        
        indx = finalIndx;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barIcon;
    private javax.swing.JLabel barIcon1;
    private javax.swing.JPanel collog;
    private javax.swing.JLabel collogL;
    private javax.swing.JPanel collogP;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton exitButton1;
    private javax.swing.JPanel fiel;
    private javax.swing.JLabel fieldL;
    private javax.swing.JPanel fieldP;
    private javax.swing.JLayeredPane headerLayPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel lang;
    private javax.swing.JLabel langL;
    private javax.swing.JPanel langP;
    private javax.swing.JLabel lblLang1;
    private javax.swing.JLayeredPane leftLayPane;
    private javax.swing.JPanel leftPane;
    private javax.swing.JLabel mobileBack;
    private javax.swing.JLabel mobileFrame;
    private javax.swing.JPanel pnlBtnAdd;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlScrPnEX;
    private javax.swing.JPanel pnlScrPnIN;
    private javax.swing.JPanel pnlScrTraEx;
    private javax.swing.JPanel pnlScrTraIn;
    private javax.swing.JPanel pnlTopHeader;
    private javax.swing.JPanel pnlTopHeader1;
    private javax.swing.JLayeredPane previewLayPane;
    private javax.swing.JScrollPane scrollPaneLang;
    private javax.swing.JScrollPane scrollPaneTran;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel titleLbl1;
    // End of variables declaration//GEN-END:variables

    private void close() {
        langOut = new OutLanguagesFile(langList);
        System.out.println("Languages printed");
        System.out.println("closing");
        System.exit(0);
    }
}
